### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by Instein98** [maxCodeVector/Monopoly#1]
I try to clone the newest repository to my server, but when I run "bash start.sh" in the server directory, it has error: Error: Could not find or load main class server.logic.MonoServer. So I had to use the server of old version.

**Comment by maxCodeVector** [comment]
I have not update my server for long time. So the server you use is the newest. For your problem, I guess you want to direct run the source code without compile them.

**Comment by Instein98** [comment]
Am I supposed to compile them? I thought that is your work!
